### ISSUE TITLE
Extreamly poor performance with 1.8 Spigot (latest)

### ISSUE THREAD

**Issue by FrozenBeard** [chaseoes/FirstJoinPlus#36]
The performance using the latest Spigot 1.8 is running at over 1500%, I had to disable the plugin until the performance is sorted out.
The task its reporting this on is FirstJoinListener$1(Single).

https://www.dropbox.com/s/q2mnvxmf8w59l7s/Screenshot%202015-02-08%2015.36.07.png?dl=0

**Comment by chaseoes** [comment]
Pastebin your configuration?

How many new players join daily?

How many unique players have you had?

**Comment by FrozenBeard** [comment]
Config: http://pastebin.com/15aCNejg
75-80 New players a day.
Just hit 20,000 uniques.

**Comment by EMGXF** [comment]
Agreed, same issue

**Comment by chaseoes** [comment]
It would be great if either of you can email me your Spigot jar.

**Comment by EMGXF** [comment]
Actually, I just upgraded to 1.8.3. I'll see if the issue persists.

**Comment by chaseoes** [comment]
Is this still an issue?

**Comment by EMGXF** [comment]
Replying from email notification (not aware of how this function works lol)

I don't really know since I quit server management a while back. From what
I recall, I think the plugin was fine after Mojang released another 1.8
sub-update.

----------------
Thanks,
~Kartik Chugh
