### ISSUE TITLE
2.3 not released

### ISSUE THREAD

**Issue by EMGXF** [chaseoes/FirstJoinPlus#37]
the readme mentions 2.3, and gives a link to the Bukkit page. However, the only version there is 2.2

**Comment by chaseoes** [comment]
It clearly said 2.3 is still in development. It's only available on my Jenkins.

**Comment by EMGXF** [comment]
Oh. Can I have the URL for your jenkins?

On Sun, May 31, 2015 at 8:16 AM, chaseoes <notifications@github.com> wrote:

> It clearly said 2.3 is still in development. It's only available on my
> Jenkins.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chaseoes/FirstJoinPlus/issues/37#issuecomment-107167673>
> .
>



-- 


----------------
Thanks,
~Kartik Chugh

A political revolution is coming. Join the movement.
<https://berniesanders.com/>
<https://berniesanders.com/>

**Comment by chaseoes** [comment]
http://ci.chaseoes.com/
