### ISSUE TITLE
player_display_name on join issue.

### ISSUE THREAD

**Issue by Antdog319** [chaseoes/FirstJoinPlus#45]
Running CraftBukkit version git-Bukkit-ed60c01 (MC: 1.9.2) (Implementing API version 1.9.2-R0.1-SNAPSHOT)

Having an issue with on join: %player_display_name

 join-message:
    enabled: true
    message: '%player_display_name&e joined the game.'
  quit-message:
    enabled: true
    message: '%player_display_name&e left the game.'

The issue is that team colors do not display on join, (default white) but does display correctly on leaving. It also displays correctly on first join, if all joins are first joins is 'true'.

Any help with this issue would be appreciated as it has been very frustrating trying to figure this out.

**Comment by chaseoes** [comment]
Try increasing the delay-everything-below-by option.

**Comment by Antdog319** [comment]
Started at 5, 10, 50 to 1000, no same result. Player name in white on join team color on leave.

**Comment by chaseoes** [comment]
Try something in-between 50 and 1000, like 200. You probably didn't wait long enough to test it at the higher values.
