### ISSUE TITLE
Spawning problem

### ISSUE THREAD

**Issue by vntqmm** [chaseoes/FirstJoinPlus#48]
Hello
I have a rather odd problem and i'm curious if you got any idea to how i can fix it.
The plugin seesm to be working properly, no error at any given time during startup or when someone joins. I've used /fjp setspawn to dedicate a spot for people joining the server for the first time, however, they continuously seem to spawn at the /spawn location.
Even more odd is, if I do /fjp debug, I spawn at the dedicated FJP spawn point.

I'm running 1.10.2 and I just updated to the newest plugin yesterday.
Any idea to what I'm doing wrong?

Kind regards and thank you for your time

**Comment by chaseoes** [comment]
Have you tried increasing the delay-everything-below-by option?

And can you upload a copy of your configuration somewhere?

**Comment by vntqmm** [comment]
Of course! I have a copy of my config for you here http://pastebin.com/xgNHx8fF

and delay-everything-below-by? - No I have not, What do you suggest I try updating the value to?

**Comment by chaseoes** [comment]
Try 5 or 10.
