### ISSUE TITLE
teleport-position: "pitch" & "yaw" inverse

### ISSUE THREAD

**Issue by RedstoneFuture** [chaseoes/FirstJoinPlus#55]

**Comment by chaseoes** [comment]
You're going to have to be a bit more specific.

**Comment by RedstoneFuture** [comment]
correctly "pitch" = "yaw" in the config
and
correctly "yaw" = "pitch" in the config

**Comment by chaseoes** [comment]
It's already correct though. According to the [Bukkit JavaDocs](https://jd.bukkit.org/org/bukkit/Location.html) this is the format for a Location object:

`Location(World world, double x, double y, double z, float yaw, float pitch)`

If you look at [line 49](https://github.com/chaseoes/FirstJoinPlus/blob/master/src/main/java/com/chaseoes/firstjoinplus/utilities/Utilities.java#L49) that's exactly how it's formatted, it uses "yaw" from the config for the yaw and the "pitch" from the config for the pitch.

**Comment by RedstoneFuture** [comment]
Yes. Sorry. My warpplugin are wrong.

**Comment by chaseoes** [comment]
You can also just stand where you want it to be and use `/fjp setspawn`.

**Comment by RedstoneFuture** [comment]
Ah ... yes, its a good idea! :) Thanks.
